# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 533e64aaca4158d4467a75e5997ad66a6dc4165d07252ceb1fac0680cd3d476943816ac5eae9f7f3ba3362a5a49a3a3eadadca3d81dd4ad2995e33fe616f4fb8

test:
  secret_key_base: 890883d773eb5ffd9f7e507e0d8df8bfd235dc023087b93c096995cab7ff780bb3a3add6f87da1fe2843d8dec9c4cbc4d5f81c2e2846ca44da7dbeede30bb806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
